config/routes.rb
Book3::Application.routes.draw do
  

  get "admin" =>'admin#index'

  controller :sessions do
    get 'login' =>:new
    post 'login' =>:create
    delete 'logout' => :destroy
  end

  resources :users  
     
     
 
  

  get "store/index"
  resources :comments
  resources :books do
    resources :comments
  end

  root :to => 'store#index', :as =>'store'  
  

    

    match 'books/:id/comments' => 'book#comments', :as => :comments

   match ':controller(/:action(/:id))(.:format)'
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :date, :book_press,:description, :image_url, :price, :title, :comments
   validates :author, :date, :description, :image_url, :price, :title, :presence =>true
   validates :title, :uniqueness =>true
   validates :image_url,:format =>{
  	:with =>%r{\.(gif|jpg|png)$}i,
  	:message =>'must be a url for gif,jpg or png image.'}
   validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
 has_many :comments

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
   skip_before_filter :authorize, :only =>[:show]
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
   def login_required
   end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "书名" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "作者" %><br />
    <%= f.text_field :author %>
  </div>
   <div class="field">
    <%= f.label "图书出版社" %><br />
    <%= f.text_field :book_press %>
  </div>
  <div class="field">
    <%= f.label "图书价格" %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label "图书简介" %><br />
    <%= f.text_area :description , :rows =>6 %>
  </div>
  <div class="field">
    <%= f.label "图书封面" %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label "出版时间" %><br />
    <%= f.date_select :date %>
  </div>
   <% if @book.title %>
  <div class="field">
  <%= f.label "这本书的评论" %><br />
  
  
  <% @book.comments.each do |comment| %>
   
    
    <tr><%=  comment.user.name if comment.user %></tr>
    <tr><%=  comment.content %></tr>
    <br />
  <% end %>
  <br />
   <%= link_to "修改评论" ,comments_url(@book) %>
  </div>
  <div class="actions">
    <%= f.submit "创建图书" %>
  </div>
 <% end %>  
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>


<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div id="book_list">
<h1>图书清单</h1>

<table>
  

<% @books.each do |book| %>
<tr class="<%= cycle('list_line_odd','list_line_even') %>">
  <td><%= image_tag(book.image_url,:class =>'list_image') %></td>
  <td class="list_description">
          <dl>
             <dt><%= book.title %> </dt>
             <dt><%= book.author %> </dt>
             <dd><%= truncate(strip_tags(book.description), :length => 80) %></dd>
             <dt><%= sprintf("￥%0.02f" , book.price) %> </dt>
             <dt><%= book.book_press %> </dt>
             <dt><%= book.date %> </dt>
             </dl>

           </td>
      
     <td class="list_action">
       <%= link_to 'Show', book %> 
    <%= link_to 'Edit', edit_book_path(book) %> 
 <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>

<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

 
 

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
  <b>书名:</b>
 <b> <%= @book.title %></b>
</p>

<p>
  <b>作者:</b>
  <%= @book.author %>
</p>

<p>
  <b>价格:</b>
  <%= @book.price %>
</p>

<p>
  <b>图书出版社:</b>
  <%= @book.book_press %>
</p>

<p>
  <b>图书简介:</b>
  <%= @book.description %>
</p>

<p>
  <b>图书封面:</b>
 <%= image_tag(@book.image_url) %> 
</p>

<p>
  <b>出版日期:</b>
  <%= @book.date %>
</p>




<h2>相关评价:</h2>
<div id="comments">
<%= render :partial => @book.comments %>
</div>
<%= form_for [@book, Comment.new] do |f| %>
  <p>
    <%= f.label :content, "新的评论" %> <br />
    <%= f.text_area :content, :rows => 5 %>
  </p>
  <p><%= f.submit "添加评论" %></p>
<% end %>
<%= link_to 'Back', store_path %>